import { ListAudit } from "./audit/ListAudit";
import { Whoami } from "./auth/Whoami";
import { DescribeCommand } from "./commands/DescribeCommand";
import { ListCommands } from "./commands/ListCommands";
import { CreateDate } from "./dates/CreateDate";
import { DeleteDate } from "./dates/DeleteDate";
import { ListDates } from "./dates/ListDates";
import { UpdateDate } from "./dates/UpdateDate";
import { CreateDiscount } from "./discounts/CreateDiscount";
import { DeleteDiscount } from "./discounts/DeleteDiscount";
import { ListDiscounts } from "./discounts/ListDiscounts";
import { UpdateDiscount } from "./discounts/UpdateDiscount";
import { CreateEvent } from "./events/CreateEvent";
import { DeleteEvent } from "./events/DeleteEvent";
import { DuplicateEvent } from "./events/DuplicateEvent";
import { ListEvents } from "./events/ListEvents";
import { PauseEvent } from "./events/PauseEvent";
import { ResumeEvent } from "./events/ResumeEvent";
import { UpdateEvent } from "./events/UpdateEvent";
import { Help } from "./help/Help";
import { Login } from "./login/Login";
import { CreateOrder } from "./orders/CreateOrder";
import { ResendOrder } from "./orders/ResendOrder";
import { ShowOrder } from "./orders/ShowOrder";
import { ResetAccount } from "./reset/ResetAccount";
import { ExportSales } from "./sales/ExportSales";
import { ListSales } from "./sales/ListSales";
import { SummarySales } from "./sales/SummarySales";
import { CreateTicket } from "./tickets/CreateTicket";
import { DeleteTicket } from "./tickets/DeleteTicket";
import { ListTickets } from "./tickets/ListTickets";
import { UpdateTicket } from "./tickets/UpdateTicket";
import type { CommandRegistration } from "../engine";

export const commandActions = [
  { route: "audit.list", Action: ListAudit },
  { route: "auth.whoami", Action: Whoami },
  { route: "commands.describe", Action: DescribeCommand },
  { route: "commands.list", Action: ListCommands },
  { route: "dates.create", Action: CreateDate },
  { route: "dates.delete", Action: DeleteDate },
  { route: "dates.list", Action: ListDates },
  { route: "dates.update", Action: UpdateDate },
  { route: "discounts.create", Action: CreateDiscount },
  { route: "discounts.delete", Action: DeleteDiscount },
  { route: "discounts.list", Action: ListDiscounts },
  { route: "discounts.update", Action: UpdateDiscount },
  { route: "events.create", Action: CreateEvent },
  { route: "events.delete", Action: DeleteEvent },
  { route: "events.duplicate", Action: DuplicateEvent },
  { route: "events.list", Action: ListEvents },
  { route: "events.pause", Action: PauseEvent },
  { route: "events.resume", Action: ResumeEvent },
  { route: "events.update", Action: UpdateEvent },
  { route: "help", Action: Help },
  { route: "login", Action: Login },
  { route: "orders.create", Action: CreateOrder },
  { route: "orders.resend", Action: ResendOrder },
  { route: "orders.show", Action: ShowOrder },
  { route: "reset", Action: ResetAccount },
  { route: "sales.export", Action: ExportSales },
  { route: "sales.list", Action: ListSales },
  { route: "sales.summary", Action: SummarySales },
  { route: "tickets.create", Action: CreateTicket },
  { route: "tickets.delete", Action: DeleteTicket },
  { route: "tickets.list", Action: ListTickets },
  { route: "tickets.update", Action: UpdateTicket },
] satisfies CommandRegistration[];
